credentials:
  usernames:
    jsmith:
      name: admin
      password: admin  # gunakan password yang di-hash
    rbriggs:
      name: user
      password: user
cookie:
  name: some_cookie_name
  key: some_random_key  # gunakan kunci rahasia
  expiry_days: 30
