credentials:
  usernames:
    joey:
      name: audit3
      password: $2y$10$LbJy8OF3XRVKFMGx8JdYlO99mdbtj7I0mYvB1C3Gsef7dMadhSEqK
      email: naeyanika@gmail.com
      roles:
        - admin
cookie:
  name: some_cookie_name
  key: some_random_key  # gunakan kunci rahasia
  expiry_days: 30
preauthorized:
  emails:
    - naeyanika@gmail.com
